name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup macOS/Linux
        if: ${{ matrix.os != 'windows-latest' }}
        run: ./setup.sh

      - name: Setup Windows
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        run: ./setup.ps1

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        if: ${{ matrix.os != 'windows-latest' }}
        run: npm run format-check

      - name: Package
        run: npm run package
        timeout-minutes: 30

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.3  # explicitly pinned version
        with:
          name: ${{ matrix.os }}-binary
          path: out
